motds:
  generic:
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  dynamic:
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cWorauf wartest du noch, &6%player&c?'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.9-1.11%newline&cDeine Insel wartet auf dich, &6%player&c!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cWorauf wartest du noch, &6%player&c?'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Survival &e+ viel mehr&8 | &71.9-1.11%newline&cDeine Insel wartet auf dich, &6%player&c!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cWorauf wartest du noch, &6%player&c?'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Build &e+ viel mehr&8 | &71.9-1.11%newline&cDeine Insel wartet auf dich, &6%player&c!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cWorauf wartest du noch, &6%player&c?'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Creative &e+ viel mehr&8 | &71.9-1.11%newline&cDeine Insel wartet auf dich, &6%player&c!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cWorauf wartest du noch, &6%player&c?'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Paintball &e+ viel mehr&8 | &71.9-1.11%newline&cDeine Insel wartet auf dich, &6%player&c!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cJetzt mit End!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cBesser als je zuvor!'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cKann Spuren von Creepern enthalten.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cKeep calm and play on Craften.'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cWorauf wartest du noch, &6%player&c?'
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Mob Arena &e+ viel mehr&8 | &71.9-1.11%newline&cDeine Insel wartet auf dich, &6%player&c!'
