motds:
  generic:
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cJetzt mit End!'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cBesser als je zuvor!'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cCraften ist metal, Craften hat Nuesse!'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cJetzt joinen und 1000 Waschmaschinen gewinnen!'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cKann Spuren von Creepern enthalten.'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cKeep calm and play on Craften.'
  dynamic:
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cWarst du schon im End, &6%player&c?'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cDeine Insel wartet auf dich, &6%player&c!'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cLust auf Paintball, &6%player&c?'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cCraften ist metal, Craften hat Nuesse!'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cCraften + &6%player&c = <3'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cKann Spuren von Creepern enthalten.'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cHey &6%player&c, jetzt joinen und Waschmaschine gewinnen!'
  - '&r&7[&cCr&6af&ete&an &2Se&3rv&9er&r&7]&6&m   &r&8[&7&oby craften.de&8]%newline&r&cKeep calm and play on Craften, &6%player&c.'
