motds:
  generic:
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.8-1.10%newline&6&lHalloween-Event&8 | &aGems, Items und mehr!'
  dynamic:
  - '&r&7&cCr&6af&ete&an &2Se&3rv&9er&r&7&8 | &6Skyblock &e+ viel mehr&8 | &71.8-1.10%newline&6&lHalloween-Event&8 | &aGems, Items und mehr!'

